# Model parameters
model:
  # - Encoder
  enc_emb_dim: 512 # Embedding output dimension
  enc_num_conv_layers: 3 # Number of convolutional layers,
  enc_conv_batchnorm: True # Set true to use batchnorm in the convolutional layers
  enc_conv_residual: True # Set true to use residual connection in conv layers
  enc_conv_channels: 512 # Convolution output channels,
  enc_conv_kernel_size: 5 # Kernel size of convolution layers
  enc_conv_dropout_rate: 0.5 # Dropout rate of convolution layers
  enc_blstm_hidden_size: 512 # Number of encoder blstm hidden units (encoder's output size)
  enc_blstm_num_layers: 1 # Number of encoder blstm layers
  # - Decoder
  dec_num_prenet_layers: 2
  dec_prenet_hidden_size: 256
  dec_num_lstm_layers: 2
  dec_lstm_hidden_size: 1024
  dec_num_postnet_layers: 5
  dec_postnet_conv_channels: 512
  dec_postnet_conv_kernel_size: 5
  dec_zoneout_rate: 0.1
  dec_dropout_rate: 0.5
  dec_batch_norm: True
  dec_out_dim: 80
  # - Speaker embedding and style vectors
  use_spk_emb: True
  spk_emb_size: 16
  num_spk: 84
  # - Attention
  attn_type: "gmmv2"
  # --- Attention: gmmv2
  attn_gmm_k: 25
  # - Reduction factor
  max_reduction_factor: 2

# ===========================================================
# Training parameters
epochs: 200
lr: 0.0001
batch_size: 5
chekpoint_save_steps: 1000
use_cuda: True

# Loss
use_weighted_masking: True
bce_pos_weight: 1.0

# Output parameters
output_path: "./outputs"
run_name: "commonvoice_fa"

# Data Parameters
num_workers: 3
datasets:
  commonvoice_fa:
    dataset_path: "/content/gdrive/MyDrive/root/datasets/cv_13_tac2"
    max_mel_len: 1000
    train_metafile: "metadata_train.txt"
    eval_metafile: "metadata_train.txt"
    speakers_list: ['speaker_fa_0',
                    'speaker_fa_1',
                    'speaker_fa_2',
                    'speaker_fa_3',
                    'speaker_fa_4',
                    'speaker_fa_5',
                    'speaker_fa_6',
                    'speaker_fa_7',
                    'speaker_fa_8',
                    'speaker_fa_9',
                    'speaker_fa_10',
                    'speaker_fa_11',
                    'speaker_fa_12',
                    'speaker_fa_13',
                    'speaker_fa_14',
                    'speaker_fa_15',
                    'speaker_fa_16',
                    'speaker_fa_17',
                    'speaker_fa_18',
                    'speaker_fa_19',
                    'speaker_fa_20',
                    'speaker_fa_21',
                    'speaker_fa_22',
                    'speaker_fa_23',
                    'speaker_fa_24',
                    'speaker_fa_25',
                    'speaker_fa_26',
                    'speaker_fa_27',
                    'speaker_fa_28',
                    'speaker_fa_29',
                    'speaker_fa_30',
                    'speaker_fa_31',
                    'speaker_fa_32',
                    'speaker_fa_33',
                    'speaker_fa_34',
                    'speaker_fa_35',
                    'speaker_fa_36',
                    'speaker_fa_37',
                    'speaker_fa_38',
                    'speaker_fa_39',
                    'speaker_fa_40',
                    'speaker_fa_41',
                    'speaker_fa_42',
                    'speaker_fa_43',
                    'speaker_fa_44',
                    'speaker_fa_45',
                    'speaker_fa_46',
                    'speaker_fa_47',
                    'speaker_fa_48',
                    'speaker_fa_49',
                    'speaker_fa_50',
                    'speaker_fa_51',
                    'speaker_fa_52',
                    'speaker_fa_53',
                    'speaker_fa_54',
                    'speaker_fa_55',
                    'speaker_fa_56',
                    'speaker_fa_57',
                    'speaker_fa_58',
                    'speaker_fa_59',
                    'speaker_fa_60',
                    'speaker_fa_61',
                    'speaker_fa_62',
                    'speaker_fa_63',
                    'speaker_fa_64',
                    'speaker_fa_65',
                    'speaker_fa_66',
                    'speaker_fa_67',
                    'speaker_fa_68',
                    'speaker_fa_69',
                    'speaker_fa_70',
                    'speaker_fa_71',
                    'speaker_fa_72',
                    'speaker_fa_73',
                    'speaker_fa_74',
                    'speaker_fa_75',
                    'speaker_fa_76',
                    'speaker_fa_77',
                    'speaker_fa_78',
                    'speaker_fa_79',
                    'speaker_fa_80',
                    'speaker_fa_81',
                    'speaker_fa_82',
                    'speaker_fa_83']
